layout_spectrum: 0.7956989
color:
  saturation: 0.6915639
  lightness: 0.3499706
  brandStrength: 0.5492969
  rhythmicContrast: 0.878777
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0.460878
name: Peter Francis-Macrae
